{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "assignment-grader.configMapName" . }}
  labels:
    {{- include "assignment-grader.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  API_PORT: "8600"
  WS_PORT: "9000"
  REDIS_URL: {{ include "assignment-grader.redisUrl" . | quote }}
{{- end }}
