{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "assignment-grader.secretName" . }}
  labels:
    {{- include "assignment-grader.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESSKEYID: {{ .Values.env.accessKeyId | quote }}
  SECRETACCESSKEY: {{ .Values.env.secretAccessKey | quote }}
  BUCKET_NAME: {{ .Values.env.bucketName | quote }}
  R2_ENDPOINT: {{ .Values.env.r2Endpoint | quote }}
  PUBLIC_ENDPOINT: {{ .Values.env.publicEndpoint | quote }}
  GEMINI_API_KEY: {{ .Values.env.geminiApiKey | quote }}
  JWT_SECRET: {{ .Values.env.jwtSecret | default "" | quote }}
  JWT_REFRESH_SECRET: {{ .Values.env.jwtRefreshSecret | default "" | quote }}
{{- end }}
