{{- if .Values.tags.ws }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "assignment-grader.fullname" . }}-ws
  labels:
    {{- include "assignment-grader.ws.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ws.service.type }}
  ports:
    - port: {{ .Values.ws.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "assignment-grader.ws.selectorLabels" . | nindent 4 }}
{{- end }}
