name: Lint & Typecheck

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    name: Backend API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: bunx prisma generate
      - run: bun run lint
      - run: bun run typecheck

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: bun run lint
      - run: bun run typecheck
